/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    DataSetInput: typeof import('./src/components/DataSetInput.vue')['default']
    OptionsList: typeof import('./src/components/OptionsList.vue')['default']
    RegexMatch: typeof import('./src/components/RegexMatch.vue')['default']
    TemplateInput: typeof import('./src/components/TemplateInput.vue')['default']
  }
}
